### ISSUE TITLE
Wording in Type 1 and Type II errors lesson misleading

### ISSUE THREAD

**Issue by anonymous2020andbeyond** [learn-co-curriculum/dsc-type-1-and-2-error#1]
## Link to Canvas

https://learning.flatironschool.com/courses/6222/assignments/226499?module_item_id=529255

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ x] Other (explain below)
Wording is confusing
### Source

```
Alpha and Type I Errors
When conducting hypothesis testing, there will almost always be the chance of accidentally rejecting a null hypothesis when it should not have been rejected. Data scientists have the ability to choose a confidence level, alpha ( 𝛼
 ) that they will use as the threshold for accepting or rejecting the null hypothesis.
```

### Concern

Alpha is referred to as confidence level instead of significance level

## (Optional) Proposed Solution

Replace confidence level with significance level

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
While we have kept the Statistical Power lesson for v3.0 of the curriculum, we have not kept the lab. As such, this repo is no longer being updated.
