### ISSUE TITLE
Issue with z-score for binomial example

### ISSUE THREAD

**Issue by daviderics** [learn-co-curriculum/dsc-type-1-and-2-error#2]
## Link to Canvas

https://learning.flatironschool.com/courses/6590/assignments/235704?module_item_id=552936

## Issue Subtype

- [x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
n = 20 #Number of flips
p = .75 #Simulating an unfair coin
coin1 = np.random.binomial(n, p)
sigma = np.sqrt(n*.5*(1-.5))
z = (coin1 - 10) / (sigma / np.sqrt(n))
```

### Concern

In this example, an unfair coin (75% chance of heads) is flipped 20 times and then a z-score is calculated assuming it is a fair coin.
In the final line I copied above, n (20) is used as the size of the sample when calculating the z-score, however, the actual sample size is just 1 (1 sample made from counting the number of heads from 20 coin flips). I can tell this result is incorrect because the code comes up with a z-score of 6 and a tiny p-value when there were 13 heads out of 20 flips, but getting 13 heads is not significantly different than getting 10 (50%). For the final line, n should just be 1 (n is correctly used when calculating sigma).

## (Optional) Proposed Solution

The n in the formula for the z-score should just be 1. At the end of the notebook, it loops through many values of n and still uses that n in the calculation of the z-score even though the sample size is 1 in each case. This should also be fixed.

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by christine-egan42** [comment]
corrected typo in the formula
