### ISSUE TITLE
"Type I and Type II errors": Error in z-score calculation

### ISSUE THREAD

**Issue by ccsurratt** [learn-co-curriculum/dsc-type-1-and-2-error#3]
## Link to Canvas

https://learning.flatironschool.com/courses/6484/assignments/241649?module_item_id=568106

## Issue Subtype

- [X] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [X] Other (explain below)
Error in formula for z-score calculation in index.ipynb

## Describe the Issue
The z-score calculation is incorrect in cell 4. 

### Source

```
z = (coin1 - 10) / (sigma / np.sqrt(n))
z
```

### Concern

In this lab, n was defined in cell 1 as 20, since we are flipping the coin 20 times.
However, in calculating the z-score, n should not be 20. 

For this binomial distribution, the mean is 10 and the standard deviation is (approximately) 2.23.

Say that in cell 2 we get an outcome of 11 heads (this is actually what I got when I initially ran this trial). If I use this value and calculate the z-score using the formula in cell 4:
    z = (11 - 10) / (sigma / np.sqrt(n))
I get a z-score of 2.0. This value doesn't make sense: my trial was less than 1 standard deviation from the mean.

This is when I realized there was an issue with the formula:
I did not conduct 20 trials with an _average_ of 11 heads. I conducted 1 trial (of 20 flips) with 11 heads.

## (Optional) Proposed Solution

Cell 4 should read:
z = (coin1 - 10) / (sigma / np.sqrt(1))
z
OR
z = (coin1 - 10) / (sigma / 1)
z

I also think it would be helpful for other students to explain in the markdown why n is a different value than it was in cell 1:
We are using a count of successes per trial of 20 flips as the expected value/mean. 
     For example, going back to the idea of getting 11 heads, the mean was 11. I conducted 1 trial with 11 heads (11/1 = 11).
     This is different than conducting 20 trials with a 11 heads: that mean would be 11/20 = 0.55.

Additionally, while the lack of random seed is what allowed me to get such an unexpected number of heads and therefore realize that there was an error here, I think it would be helpful to include a random seed for future students. Given the output that I got, much of the markdown contradicted what I was actually experiencing with my results.

## What OS Are You Using?

- [X] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by ccsurratt** [comment]
Just took a look at the other issues for this lab and saw a similar issue reported.

It appears that this issue was fixed in the README, but it is still present in index.ipynb.

**Comment by Cheffrey2000** [comment]
The issue has been fixed on the curriculum branch notebook (index.ipynb) and the changes will automatically sync accross branches and to the README.md files. The commit can be found here: [b56c662](https://github.com/learn-co-curriculum/dsc-type-1-and-2-error/commit/b56c6628d923c19cd0e3d1a23139d0930dc3da66)
